### ISSUE TITLE
control parameter in mvJointModelBayes

### ISSUE THREAD

**Issue by penglistat** [drizopoulos/JMbayes#102]
Dear Prof. Rizopoulos, 
We are trying to use mvJointModelBayes. There are 2 questions confused us very much.
1. For the summarizing the reuslts from mvJointModelBayes, while using weights, as summary(obj, weighted=TRUE), the estimation of StDev would be "Inf" or "NaN". Is this because there were too less iterations? On line 965 of mvJointModelBayes, it is coded as "wStDev = summary_fun(wsd, weights = weights),". Would  "wStDev = summary_fun(wsd, weights = weights, na.rm = TRUE)," fix this missing?

2. Also related with this problem, we try to use larger n_iter in the simulation. There was always error: 
   "Error in dimnames(x) <- dn:
              length of "dimnames" [2] not equal to array extent ". 
    We try different n_iter and n_thin, while only when n_iter =n_thin there would be no error. Our question is whether it is correct to set n_iter = 5000 and n_thin = 5000 and report 95%C without valiady estimation of StDev?

Many thanks in advance!
Best wishes, 
Peng

**Comment by drizopoulos** [comment]
Try JMbayes2

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
From: penglistat ***@***.***>
Sent: Monday, July 3, 2023 5:09:30 PM
To: drizopoulos/JMbayes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [drizopoulos/JMbayes] control parameter in mvJointModelBayes (Issue #102)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Dear Prof. Rizopoulos,
We are trying to use mvJointModelBayes. There are 2 questions confused us very much.

  1.  For the summarizing the reuslts from mvJointModelBayes, while using weights, as summary(obj, weighted=TRUE), the estimation of StDev would be "Inf" or "NaN". Is this because there were too less iterations? On line 965 of mvJointModelBayes, it is coded as "wStDev = summary_fun(wsd, weights = weights),". Would "wStDev = summary_fun(wsd, weights = weights, na.rm = TRUE)," fix this missing?

  2.  Also related with this problem, we try to use larger n_iter in the simulation. There was always error:
"Error in dimnames(x) <- dn:
length of "dimnames" [2] not equal to array extent ".
We try different n_iter and n_thin, while only when n_iter =n_thin there would be no error. Our question is whether it is correct to set n_iter = 5000 and n_thin = 5000 and report 95%C without valiady estimation of StDev?

Many thanks in advance!
Best wishes,
Peng
