### ISSUE TITLE
Multivariate LME

### ISSUE THREAD

**Issue by GusDM** [drizopoulos/JMbayes#27]
Hi,
Would it be possible to fit a second linear mixed effects model - with different dependent variable - instead of the time-to-event model?
Thank you!

**Comment by drizopoulos** [comment]
Yes, using function mvglmer().

**Comment by sgachau** [comment]
Dear Prof. Rizopoulos,

Thank you for  JMbayes package  which is very helpful.
 I  am  fitting a model  with  four  longitudinal  outcomes and since   i  don't have a  time-to-event  outcome  am  using function mvglmer() function.     I would like to  know whether this qualifies  as a joint model. I would also  like to know  whether shared parameter assumption hold for  mvglmer().

 Thank you 
Sgachau

**Comment by drizopoulos** [comment]
Yes, this is also a joint model.

**Comment by sgachau** [comment]
Thank  you  for the  clarification
Regards
