### ISSUE TITLE
Intercept Term in mvglmer() Cannot be omitted

### ISSUE THREAD

**Issue by ngwali** [drizopoulos/JMbayes#58]
Hello Dimitry;
I couldn't fit a mixed effect model without omitting the intercept term in  mvglmer() 

for instance

Option 1: mvglmer(list(biormarker~-1+Treat+ Treat:time+(time|id)), families=list(gaussian), engine="JAGS")
Option 2: mvglmer(list(biormarker~0 +Treat+ Treat:time+(time|id)), families=list(gaussian), engine="JAGS")

The two options will always produce an intercept term and I cannot estimate the effect of the binary treatment variable (Treat0 and Treat1 ). Rather I get effects only for treatment 1.

I also tried creating two dummy variables for treatment, i.e Treat0 and Treat1, but the intercept term is still included, and so causes the Rhat values to be very high for this two variables, hence poor sampling.

I will be very much happy if you help me out with this.

Thank you

**Comment by drizopoulos** [comment]
Indeed, because mvglmer() uses hierarchical centering by default this is not possible. You could calculate statistics for the effect of interest using the MCMC output.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
