### ISSUE TITLE
Error in IndvPred_lme 

### ISSUE THREAD

**Issue by Noemiglois** [drizopoulos/JMbayes#86]
Hi @drizopoulos ,

We have trained a Linear Mixed Effects (LME) model with some longitudinal data and we want to make use of your IndvPred_lme function in order to predict some new data (also longitudinal) to obtain subject-level predictions. We get an error (see below) when we try to dynamic predict some of the new subjects, but for the grand majority, it works well. 

_Error in col(ind): a matrix-like object is required as argument to 'col'._

The code we are using is:
![image](https://user-images.githubusercontent.com/26384690/137127857-be9571d2-dbd3-41fa-936f-2196405cfa70.png)

RStudio version:    1.3.1093 (2009-2020)
R version:              4.0.3 (2020-10-10)
IndvPred_lme (from JMbayes package version 0.8-85)
lme (from nlme package version 3.1-149)

As for the moment, we just deleted those subjects (less than 1%) that gave us an error, in order to continue with our workflow, but we would like to know why this is happening and if it would be possible to fix it.

Thanks in advance!!
Noemi

**Comment by drizopoulos** [comment]
I would need a reproducible example.



——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
From: Noemi Gonzalez Lois ***@***.***>
Sent: Wednesday, October 13, 2021 1:56:50 PM
To: drizopoulos/JMbayes ***@***.***>
Cc: Dimitris Rizopoulos ***@***.***>; Mention ***@***.***>
Subject: [drizopoulos/JMbayes] Error in IndvPred_lme (#86)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi @drizopoulos<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdrizopoulos&data=04%7C01%7Cd.rizopoulos%40erasmusmc.nl%7C7212cf656e244441366608d98e408bb6%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637697230140014185%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YgFBkrXhuGK4zrsI6nHhxIFVlBvP1PCkBjY1H2CaxU8%3D&reserved=0> ,

We have trained a Linear Mixed Effects (LME) model with some longitudinal data and we want to make use of your IndvPred_lme function in order to predict some new data (also longitudinal) to obtain subject-level predictions. We get an error (see below) when we try to dynamic predict some of the new subjects, but for the grand majority, it works well.

Error in col(ind): a matrix-like object is required as argument to 'col'.

The code we are using is:
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F26384690%2F137127857-be9571d2-dbd3-41fa-936f-2196405cfa70.png&data=04%7C01%7Cd.rizopoulos%40erasmusmc.nl%7C7212cf656e244441366608d98e408bb6%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637697230140024143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YG9VB5yizSuKPhuN8ph3LGgey8FygdMFssVzz2gRUCs%3D&reserved=0>

RStudio version: 1.3.1093 (2009-2020)
R version: 4.0.3 (2020-10-10)
IndvPred_lme (from JMbayes package version 0.8-85)
lme (from nlme package version 3.1-149)

As for the moment, we just deleted those subjects (less than 1%) that gave us an error, in order to continue with our workflow, but we would like to know why this is happening and if it would be possible to fix it.

Thanks in advance!!
Noemi

**Comment by Noemiglois** [comment]
Hi again! I have just sent you an email off-list with a short version of our code, which you can execute to reproduce the error we mentioned. 

Thanks!!
Noemi

**Comment by Noemiglois** [comment]
Just an update in case someone else runs into the same problem: 

This error was solved by changing the argument "all_times = F" by "all_times=T". 

The problem was that the argument "times=100" by default, and for some subjects in the test partition the age was larger than the maximum age in the train partition.

Noemi
